require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - bin/**/*
    - spec/dummy/bin/**/*
    - spec/dummy/db/migrate/*
    - spec/dummy/db/schema.rb


  DisplayCopNames: true

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false


Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/IndentFirstHashElement:
  EnforcedStyle: 'consistent'

Layout/AlignParameters:
  EnforcedStyle: 'with_fixed_indentation'

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Layout/IndentFirstArgument:
  EnforcedStyle: consistent


Metrics/LineLength:
  Max: 128
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - spec/dummy/config/**/*
    - spec/dummy/Rakefile
  

Metrics/BlockLength:
  Max: 35
  Exclude:
    - spec/to_hash/**/*


Metrics/MethodLength:
  Max: 20

Rails/HttpPositionalArguments:
  Exclude:
    - "spec/dummy/config/routes.rb"

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Style/MultilineBlockChain:
  Enabled: false

Metrics/AbcSize:
  Max: 22

Metrics/ModuleLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Style/RegexpLiteral:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - spec/dummy/app/controllers/**/*

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver